---
title: ""
---

## About

This is where you can respond with your results from the first practical exercise and find details regarding the second practical exercise. First, you will find a series of polls where you can respond with your findings from the first practical exercise. You will then find details regarding the second practical exercise that will occur later in RStudio. As always, if you have any questions please reach out!

## Practical Exercise 1

Prior to the first practical exercise, please make sure MATLAB and other necessary packages are downloaded. Additional needed packages include:

-   Curve Fitting Toolbox
-   Global Optimization Toolbox
-   Optimization Toolbox
-   Signal Processing Toolbox
-   Simulink
-   Statistics
-   Machine Learning Toolbox

*Slides:* Coming Soon. 

*Other Needed Materials*

Coming Soon.

<iframe src="https://pollev-embeds.com/multiple_choice_polls/AJxVjgiOmkTW1grpSzb39/respond" width="800px" height="600px">

</iframe>

<iframe src="https://pollev-embeds.com/multiple_choice_polls/wkPRU4ha7qQXZgO70kC2w/respond" width="800px" height="600px">

</iframe>

<iframe src="https://pollev-embeds.com/multiple_choice_polls/1ax0JeJ6s8pty68BvzZDS/respond" width="800px" height="600px">

</iframe>

<iframe src="https://pollev-embeds.com/multiple_choice_polls/pQieIvhUTg1GrmWrFdwXq/respond" width="800px" height="600px">

</iframe>

## Practical Exercise 2

Prior to the second practical exercise, please make sure R, RStudio, RStan and other necessary packages are downloaded. Additional needed packages include:

-   learnr
-   tidyverse
-   tinytex
-   rstan
-   bayesplot
-   rstantools
-   desolve.

Please refer to the [Additional Resources](additionaDetails.qmd) page for tutorials related to downloaded the needed software and packages.
