---
title: ""
---

## Software Resources

### Apporto Virtual Desktop

**Login Portal:** https://rsphemory.apporto.com/

**Slides:** [Apporto Virtual Desktop Tutorial](Powerpoints/apporto.pdf)

Covers

-   Logging into the desktop
-   Uploading data
-   Downloading data

### MATLAB

**Online Tutorial:** [MATLAB Tutorial](https://www.mathworks.com/support/learn-with-matlab-tutorials.html)

**Slides:** [Exploring MATLAB](Powerpoints/ExploringMATLAB.pdf)

Covers

-   General Structure
-   Adding Packages

### R & RStudio

**Link to download R:** [CRAN-R](https://cran.r-project.org/)

**Link to download RStudio:** [Posit](https://posit.co/download/rstudio-desktop/)

**RStudio Tutorial(s):** [Code Recipes](https://posit.cloud/learn/recipes?_gl=1*1q88cu3*_ga*MTE1NDU3OTExMS4xNzIxMDUzMTEw*_ga%202C0WZ1JHG0*MTcyMTA1MzExMC4zLjEuMTcyMTA1MzEyNS4wLjAuMA.)

**RStudio Cheatsheets:** [Cheatsheets](https://rstudio.github.io/cheatsheets/contributed-cheatsheets.html)

The above two links contains multiple tutorials related to various aspects of RStudio ranging from basic usage to package-specific details.

**R Basics Tutorial Video**

<iframe width="560" height="315" src="https://www.youtube.com/embed/FY8BISK5DpM?si=EBo6GnQmHMVJ7i9l" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen>

</iframe>

## Tutorial Resources

### *QuantDiffForecast*

**Slides:** [QuantDiffForecast Overview](Powerpoints/QuantDiffForecast.pdf)

Covers

-   General Structure
-   Preparing the toolbox
-   Workflow

**Tutorial Paper:** Chowell G, Bleichrodt A, Luo R. Parameter estimation and forecasting with quantified uncertainty for ordinary differential equation models using QuantDiffForecast: A MATLAB toolbox and tutorial. Stat Med. 2024 Apr 30;43(9):1826-1848. doi: [10.1002/sim.10036](https://doi.org/10.1002/sim.10036). Epub 2024 Feb 20. PMID: 38378161; PMCID: PMC11031352.

**Tutorial Video**

<iframe width="560" height="315" src="https://www.youtube.com/embed/eyyX63H12sY?si=hW9j9yN6ZiyUq_N8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen>

</iframe>

### *RStan*

**Website:** [Rstan](https://mc-stan.org/users/interfaces/rstan)

**Tutorial:** [RStan GitHub](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started)

Covers

-   Installing RStan
-   Basic usuage examples
