---
title: ""
---

## Meeting Times

-   Monday, July 22, 8:30 AM – 5:00 PM
-   Tuesday July 23, 8:30 AM – 5:00 PM
-   Wednesday July 24, 8:30 AM – 12:00 PM

Classroom: Randall Rollins Building (RR 200)

## Module Summary

Mathematical models based on systems of ordinary differential equations (ODEs) are frequently applied in various scientific fields to assess hypotheses, estimate key model parameters, and generate predictions about the system's state. To support their application, this module introduces frequentist and Bayesian methods for estimating parameters and generating short-term forecasts with quantified uncertainty from dynamical models. Motivating practical examples will be based on epidemic models with varying levels of complexity. The course includes a general introduction to Bayesian statistics, Monte Carlo, and MCMC.

The course includes a general introduction to Bayesian statistics, Monte Carlo, and MCMC. Some relevant facts from the Markov chain theory are reviewed. Algorithms include Gibbs sampling and Metropolis-Hastings. A practical introduction to convergence diagnostics is included. The module will alternate between lectures and computer labs.

## Prerequisites

This module assumes knowledge of probability and inference covered in an introductory statistical course. Students will learn to use R and MATLAB toolboxes designed for parameter estimation and forecasting using dynamic models. Students are expected to have basic knowledge of the R computing environment. Students new to R should complete a tutorial before the module.

## Required Software

**Software:** R, R-Studio, MATLAB (The Mathworks, Inc.)

**R Packages:** Stan

**MATLAB Packages:** Curve Fitting Toolbox, Global Optimization Toolbox, Optimization Toolbox, Signal Processing Toolbox, Simulink, Statistics and Machine Learning Toolbox

Emory has also provided us with access to the Apporto Virtual Desktop. This desktop contains the required MATLAB software, and comes pre-loaded with the needed MATLAB packages. If MATLAB is not available on the local system, please use Apporto. R and RStudio are free to download on your local system. Additional details regarding the set-up for the required software can be found within the [Additional Resources](additionaDetails.qmd) page.

## Module Content

-   Brief review of ordinary differential equation models applied to infectious disease transmission and control.

-   Introduction to parameter identifiability

-   Introduction to uncertainty quantification using parametric bootstrapping

-   Model selection and assessing the quality of model fit

-   Introduction to Bayesian statistics, Monte Carlo, and MCMC

-   Bayesian modeling framework for fitting and forecasting epidemic trajectories in Stan

-   Model-based forecasts with quantified uncertainty

-   Metrics for assessing calibration and forecasting performance

## Instructors

### Gerardo Chowell, PhD
Professor and Chair, Department of Population Health Sciences, Georgia State University

Dr. Chowell's research focuses on developing and applying mathematical and statistical methods for investigating the spread and control of emerging and re-emerging pathogens. Recent works includes leading the development of various toolboxes for fitting and forecasting disease trends.

**Email:** gchowell@gsu.edu 

### Nick Hengartner, PhD 
Acting Director, Center for Nonlinear Studies, Los Alamos National Laboratory.

**Email:** nickh@lanl.gov

### TA: Amanda Bleichrodt, MPH
Doctoral Student, Department of Population Health Sciences, Georgia State University

Amanda is this course's teaching assistant and a 2CI fellow in Dr. Gerardo Chowell's lab. Her research interests include exploring diverse modeling methodologies for forecasting disease outbreaks and developing user-friendly forecasting tools. Recent works include evaluating model performance in forecasting the recent mpox outbreak and real-time forecasting of multiple disease types. 

**Email:** ableichrodt1@student.gsu.edu

## Schedule

|      Time       |                                         Day 1                                         |                         Day 2                         |                             Day 3                              |
|:-------------:|:-----------------------:|:-------------:|:----------------:|
|  8:30-10:00 am  |                Review of epidemic models (deterministic and stochastic                | Intro to Bayesian inference, Monte Carlo Markov Chain | Bayesian inference for fitting and forecasting epidemic models |
| 10:00-10:30 am  |                                        *Break*                                        |                        *Break*                        |                            *Break*                             |
| 10:30-12:00 pm  | Parameter identifiability. Frequentist approach to fitting and forecasting epidemics. |                 MCMC algorithms + Lab                 |                       Practical Exercise                       |
| 12:00 - 1:30 pm |                                     *Lunch Break*                                     |                     *Lunch Break*                     |                               \-                               |
| 1:30 - 3:00 pm  |                  Parameter estimation and forecasting tutorial + Lab                  |               The Art of MCMC Sampling                |                               \-                               |
| 3:00 - 3:30 pm  |                                        *Break*                                        |                        *Break*                        |                               \-                               |
| 3:30 - 5:00 pm  |                                  Practical Exercise                                   |               Data augmentation methods               |                               \-                               |
